# Site/SEO settings
email:
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics:

name: Tommy Worung
title: Studio 010
description: >
  Studio 010 is a photo blog made by Tommy Worung.
url:
twitter_username:
default_img: /assets/images/cats.jpg
social:
  - name: facebook
    url:
  - name: instagram
    url: https://www.instagram.com/tommy.ill.figure/
  - name: linkedin
    url:
  - name: twitter
    url:
  - name:
    url:

# Contact settings
contact_img: /assets/images/cats.jpg
# formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
# mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
# mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Tommy Worung
    bio:
    url:

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: 'Studio 010'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
